services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - gateway1
      - gateway2
      - gateway3

  gateway1:
    build: ./backend/gateway
    env_file:
      - ./backend/gateway/.env
    environment:
      - SERVER_NAME=FIRST GATEWAY
    ports:
      - "8009:8008"
    depends_on:
      - auth-service
      - product-service
      - order-service

  gateway2:
    build: ./backend/gateway
    env_file:
      - ./backend/gateway/.env
    environment:
      - SERVER_NAME=SECOND GATEWAY
    ports:
      - "8010:8008"
    depends_on:
      - auth-service
      - product-service
      - order-service

  gateway3:
    build: ./backend/gateway
    env_file:
      - ./backend/gateway/.env
    environment:
      - SERVER_NAME=THIRD GATEWAY
    ports:
      - "8011:8008"
    depends_on:
      - auth-service
      - product-service
      - order-service

  auth-service:
    build: ./backend/services/auth
    env_file:
      - ./backend/services/auth/.env
    ports:
      - "7001:8001"

  product-service:
    build: ./backend/services/product
    env_file:
      - ./backend/services/product/.env
    ports:
      - "7002:8002"

  order-service:
    build: ./backend/services/order
    env_file:
      - ./backend/services/order/.env
    ports:
      - "7003:8003"
