events {}

http {
    upstream gateway {
        server gateway1:8008;
        server gateway2:8008;
        server gateway3:8008;
    }

    server {
        listen 80;
        location / {
            proxy_pass http://gateway;
        }
    }
}
