services:
  nginx:
    image: nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  server1:
    build: ./server
    env_file:
      - ./server/.env
    environment:
      - SERVER_NAME=PEHLA SERVER
    ports:
      - "4001:6000"

  server2:
    build: ./server
    env_file:
      - ./server/.env
    environment:
      - SERVER_NAME=DOOSRA SERVER
    ports:
      - "4002:6000"

  server3:
    build: ./server
    env_file:
      - ./server/.env
    environment:
      - SERVER_NAME=TISRA SERVER
    ports:
      - "4003:6000"

